# MaCFP workflow

name: MaCFP-1_Build_LaTeX

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ master ]
    paths:
      - .github/workflows/MaCFP-1_Build_LaTeX.yml
      - Documents/MaCFP-1/**
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/MaCFP-1_Build_LaTeX.yml
      - Documents/MaCFP-1/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: pdflatex report
        uses: dante-ev/latex-action@latest
        with:
          root_file: macfp_2017_gasphase.tex
          working_directory: ./Documents/MaCFP-1
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex report
        uses: dante-ev/latex-action@latest
        with:
          root_file: macfp_2017_gasphase.aux
          working_directory: ./Documents/MaCFP-1
          compiler: bibtex
          args:
      - name: pdflatex report
        uses: dante-ev/latex-action@latest
        with:
          root_file: macfp_2017_gasphase.tex
          working_directory: ./Documents/MaCFP-1
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: pdflatex report
        uses: dante-ev/latex-action@latest
        with:
          root_file: macfp_2017_gasphase.tex
          working_directory: ./Documents/MaCFP-1
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      # Push updated pdf to release
      - name: Upload document to releases
        if: ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && github.repository_owner == 'MaCFP'
        run: |
          gh release upload macfp-1.0 ./Documents/MaCFP-1/macfp_2017_gasphase.pdf --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

